name: CodSpeed

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ '**' ]
  # `workflow_dispatch` allows CodSpeed to trigger backtest
  # performance analysis in order to generate initial data.
  workflow_dispatch:

permissions:
  contents: read
  # Required for the OpenID Connect authentication with CodSpeed.
  id-token: write

env:
  CARGO_TERM_COLOR: always

jobs:
  benchmarks:
    name: Run benchmarks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # 6.0.2
      - name: Setup Rust toolchain, cache and cargo-codspeed binary
        uses: moonrepo/setup-rust@abb2d32350334249b178c401e5ec5836e0cd88d3 # 1.3.0
        with:
          channel: stable
          cache-target: release
          bins: cargo-codspeed
      - name: Build the benchmark targets
        run: cargo codspeed build
      - name: Run the benchmarks
        uses: CodSpeedHQ/action@373d6868929f444bc08d901fd0eb0ad52a8875ea # 5.2.1
        with:
          mode: simulation
          run: cargo codspeed run
